#!/usr/bin/env python3
"""
Generate VMD selection variables for collagen crosslink types.

This helper focuses on VMD selections only (no CSV/NDX outputs).
It defines one selection per crosslink type for both atomistic and coarse-grained
workflows.

Usage:
  python scripts/extract_atomistic_crosslinks.py
  python scripts/extract_atomistic_crosslinks.py --out my_crosslink_selections.vmd.tcl

Then in VMD:
  source crosslink_selections.vmd.tcl
  set s [atomselect top $sel_aa_PYD]
  $s num
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List


# Crosslink types requested by user and the residue names used by ColBuilder.
# These names come from src/colbuilder/data/sequence/crosslinks.csv.
TYPE_TO_RESNAMES: Dict[str, List[str]] = {
    "PYD": ["LY2", "LY3", "LYX"],
    "DPD": ["LX2", "LX3", "LXX"],
    "HLKNL": ["L4Y", "L5Y"],
    "LKNL": ["L4X", "L5X"],
    "deHHLNL": ["LY4", "LY5"],
    "deHLNL": ["LX4", "LX5"],
}


def _selection_from_resnames(resnames: List[str]) -> str:
    return "resname " + " ".join(resnames)


def build_tcl() -> str:
    lines: List[str] = []

    lines.append("# VMD selections generated by extract_atomistic_crosslinks.py")
    lines.append("#")
    lines.append("# These residue-name selections work for both atomistic and Martini CG")
    lines.append("# structures generated by ColBuilder, since crosslink residue names are")
    lines.append("# preserved across both representations.")
    lines.append("")

    for x_type, resnames in TYPE_TO_RESNAMES.items():
        sel = _selection_from_resnames(resnames)
        lines.append(f"# {x_type}: {', '.join(resnames)}")
        lines.append(f"set sel_aa_{x_type} \"{sel}\"")
        lines.append(f"set sel_cg_{x_type} \"{sel}\"")
        lines.append("")

    all_resnames = sorted({r for rs in TYPE_TO_RESNAMES.values() for r in rs})
    all_sel = _selection_from_resnames(all_resnames)
    lines.append("# Combined selection across all configured crosslink types")
    lines.append(f"set sel_aa_ALL_XLINK \"{all_sel}\"")
    lines.append(f"set sel_cg_ALL_XLINK \"{all_sel}\"")
    lines.append("")

    lines.append("# Example usage in VMD:")
    lines.append("# set x [atomselect top $sel_aa_PYD]")
    lines.append("# mol addrep top")
    lines.append("# mol modselect [expr {[molinfo top get numreps]-1}] top $sel_aa_PYD")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate VMD crosslink selection variables for atomistic and CG systems."
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("crosslink_selections.vmd.tcl"),
        help="Output Tcl file path (default: crosslink_selections.vmd.tcl).",
    )
    args = parser.parse_args()

    tcl = build_tcl()
    out_path = args.out.resolve()
    out_path.write_text(tcl)
    print(f"Wrote VMD selections: {out_path}")


if __name__ == "__main__":
    main()
